// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoL3Cc7YqXQWSDkvjHvRCtnrivNcMY5u0',
    appId: '1:1098285269241:web:f63a048e3333034f65a228',
    messagingSenderId: '1098285269241',
    projectId: 'porteco-c54ee',
    authDomain: 'porteco-c54ee.firebaseapp.com',
    storageBucket: 'porteco-c54ee.appspot.com',
    measurementId: 'G-GKQNYS3Q2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-RQqRYbAY87Wc1AJu8qHMC8NLrdExWuA',
    appId: '1:1098285269241:android:95d9d5d91e18b9c365a228',
    messagingSenderId: '1098285269241',
    projectId: 'porteco-c54ee',
    storageBucket: 'porteco-c54ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR3NjaEb1RD20kv2Pg5qhqO0zwau4mo_A',
    appId: '1:1098285269241:ios:427c3ea981c7517e65a228',
    messagingSenderId: '1098285269241',
    projectId: 'porteco-c54ee',
    storageBucket: 'porteco-c54ee.appspot.com',
    iosClientId: '1098285269241-d93337gu806nk4vifua567qqnb160vig.apps.googleusercontent.com',
    iosBundleId: 'com.example.porteco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR3NjaEb1RD20kv2Pg5qhqO0zwau4mo_A',
    appId: '1:1098285269241:ios:427c3ea981c7517e65a228',
    messagingSenderId: '1098285269241',
    projectId: 'porteco-c54ee',
    storageBucket: 'porteco-c54ee.appspot.com',
    iosClientId: '1098285269241-d93337gu806nk4vifua567qqnb160vig.apps.googleusercontent.com',
    iosBundleId: 'com.example.porteco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoL3Cc7YqXQWSDkvjHvRCtnrivNcMY5u0',
    appId: '1:1098285269241:web:30616051a027654565a228',
    messagingSenderId: '1098285269241',
    projectId: 'porteco-c54ee',
    authDomain: 'porteco-c54ee.firebaseapp.com',
    storageBucket: 'porteco-c54ee.appspot.com',
    measurementId: 'G-3BXCHRVCRB',
  );
}
